apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: react-go-app
            repoURL: https://github.com/frallan97/react-go-app.git
            targetRevision: main
            path: charts/react-go-app


  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # This tells Argo CD to create the namespace if missing:
        syncOptions:
        - CreateNamespace=true
